### ISSUE TITLE
cargo chef cook might be ignoring ./rust-toolchain.toml

### ISSUE THREAD

**Issue by colelawrence** [LukeMathWalker/cargo-chef#94] opened 2021-09-10 17:46 UTC
I'm not exactly sure if this is happening as a result of cargo chef, but it seems to be based on my investigations into our `dive` results.
<img width="725" alt="image" src="https://user-images.githubusercontent.com/2925395/132895821-864019c0-6cc3-411a-bb51-de3d7dc689c1.png">
If this sounds like something that isn't a dumb mistake on my part, I can work on making a repro.

**Comment by colelawrence** [comment] 2021-09-11 02:41
Perhaps this is caused by a call to `cargo metadata`?

**Comment by LukeMathWalker** [comment] 2021-09-11 07:35
There is a lot of stuff in that screenshot - can you summarise what you are expecting compared to what you see?

**Comment by colelawrence** [comment] 2021-09-11 15:05
@LukeMathWalker, yes, of course.

This is the output from using the [`dive` cli tool for dissecting docker layer sizes](https://github.com/wagoodman/dive).

I opened this image by running the equivalent of `dive my-registry:5000/my-image`

On the left is each step of a built docker file, on the right shows the entire filesystem for the selected layer & the modifications that the layer made.

On the left, we can see that we have the following steps performed in this order:

 * copied a rust-toolchain.toml to `./rust-toolchain.toml`
 * RUN `rust show` to install components needed for this folder
 * copied the `./recipe.json` from a planner image
 * RUN `cargo chef cook` to install components needed for this folder based on the `recipe.json`

I have the `cargo chef cook` layer highlighted, and on the left we can see (in green) that another toolchain `nightly-2021-09-07` has been added during this layer's execution.
 
This toolchain is not mentioned in the docker base image (rust-1.54.0-bullseye), but it is mentioned in an earlier installation of Cranelift.

`/usr/bin/cargo` is soft linked to cranelift cargo.

It sounds like you might be interested in what's going on here, so I'll try to construct a minimal image to help with investigation. I just want to flag this in case something immediately comes to your mind about what I should look into.

**Comment by LukeMathWalker** [comment] 2021-10-17 10:36
Any luck on the minimal image? @colelawrence

**Comment by colelawrence** [comment] 2021-11-07 03:05
Sorry, this fell off my radar, and I won't have capacity to resume looking into this until maybe next year.

**Comment by LukeMathWalker** [comment] 2022-07-04 15:49
This is likely a duplicate of #108, closing.

**Closed by LukeMathWalker** 2022-07-04 15:49 UTC
Labels: waiting for information
