### ISSUE TITLE
Use of rust-toolchain.toml

### ISSUE THREAD

**Issue by ThomWright** [LukeMathWalker/cargo-chef#108] opened 2022-01-20 15:18 UTC
## Problem
I'm working through Zero To Production, and early on decided to use a `rust-toolchain.toml` file to make it easy to [re-use the same toolchain](https://rust-lang.github.io/rustup/overrides.html) whenever I'm working on the repo.

I found that when using `chargo-chef` I wasn't getting nice quick builds, I assume because everything was getting built with an unexpected toolchain.

## Workaround
Adding the `rust-toolchain.toml` file to `.dockerignore` solved the issue.

## Proposed solution
I don't know whether this is something worth "fixing" inside `cargo-chef`, but it might be worth adding something to the documentation to warn people about this problem.

I expect that making Docker ignore the file is the correct thing to do here. In my case though, I'd forgotten I had the file, and didn't consider that it might be interfering with Docker builds. I expect I won't be the only one this happens to!

## Reproduction
You can use my repo [here](https://github.com/ThomWright/zero2prod/tree/250bcb31935637cccdc66587643f8927bb23416f) to reproduce - comment out the appropriate line in `.dockerignore` to see the problem.

## More details
For reference, the content of my `rust-toolchain.toml` file is:

```toml
[toolchain]
channel = "nightly-2021-12-23"
```

And the relevant output from `docker build --tag zero2prod --file Dockerfile .` when the toolchain file wasn't ignored:

```
...
Step 5/18 : RUN cargo chef prepare --recipe-path recipe.json
 ---> Running in c1ec9fedadd0
info: syncing channel updates for 'nightly-2021-12-23-x86_64-unknown-linux-gnu'
info: latest update on 2021-12-23, rust version 1.59.0-nightly (34926f0a1 2021-12-22)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
Removing intermediate container c1ec9fedadd0
 ---> ad3aa0cecb17
Step 6/18 : FROM chef as builder
 ---> 26248348bb3c
Step 7/18 : COPY --from=planner /app/recipe.json recipe.json
 ---> Using cache
 ---> 1526e47e0ecf
Step 8/18 : RUN cargo chef cook --release --recipe-path recipe.json
 ---> Using cache
 ---> 9668a6505a63
Step 9/18 : COPY . .
 ---> 468d574e281e
Step 10/18 : ENV SQLX_OFFLINE true
 ---> Running in 9f54f51f2745
Removing intermediate container 9f54f51f2745
 ---> 907d6ba1ccc3
Step 11/18 : RUN cargo build --release --bin zero2prod
 ---> Running in 065dd9de9454
info: syncing channel updates for 'nightly-2021-12-23-x86_64-unknown-linux-gnu'
info: latest update on 2021-12-23, rust version 1.59.0-nightly (34926f0a1 2021-12-22)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
...
```

**Comment by LukeMathWalker** [comment] 2022-03-21 08:58
This is an interesting one.

From a tooling perspective, we could emit a warning when we detect a toolchain file.
On the flip side, if you are using the same toolchain _consistently_ across all layers, you should get caching anyway 🤔

**Comment by ThomWright** [comment] 2022-03-21 10:08
Hmm yes I expect that's true 🤔 

Are there any reasons that spring to mind why some parts of the build would use a different toolchain than that specified in the `rust-toolchain.toml` file?

I can't remember the details here, but happy to run it again later to see if I can reproduce.

**Comment by LukeMathWalker** [comment] 2022-03-21 15:30
Not really. 
My guess would be - was it actually rebuilding or did you just notice it was taking longer because each layer had to download and install the toolchain from scratch?

**Comment by ThomWright** [comment] 2022-03-21 15:34
A great question, that could very well be. I have no memory of this ~place~ issue 😅 

I'll add this to my to-do list.

**Comment by LukeMathWalker** [comment] 2022-05-24 09:00
Can you provide a minimal reproducible example for us to look at the issue? @jsimonrichard

**Comment by jsimonrichard** [comment] 2022-05-25 00:30
Here it is: https://github.com/jsimonrichard/chef-toolchain-reprex

You can run it, but it'll take about 10 minutes. I did upload my log files, though, so you could take a look at those instead if you're so inclined.

**Comment by jsimonrichard** [comment] 2022-05-25 00:31
I forked the repo, though, and I think I have a solution. I'll let you know if it works after I test it

**Comment by jsimonrichard** [comment] 2022-05-25 01:31
Alright, I've done some testing, and there's one main confounding issue.

I can add *rust-toolchain.toml* to the Skeleton struct and have it recreated when `cargo chef cook` runs, but the issue is that when cargo runs (before the subcommand cargo-chef runs), it sets some environment variables. Or, at least, I'm assuming that cargo is the one setting those environment vars. It's the only thing that makes sense to me. One of those variables is `CARGO`, which follows this pattern.

```bash
CARGO=~/.rustup/toolchains/<toolchain name>/bin/cargo
```

So, essentially, the toolchain is set before we can recreate *rust-toolchain.toml*.

The solution I'm proposing is remove `cargo build` from `cargo chef cook`. I know that's a big API change, but if `cargo` runs again after chef then my assumption is that it will recalculate the environment variables. I know that running `cargo build` after chef but *before* the rest of the project files are copied over results in a build using the correct toolchain.

**An aside:** I don't think that manually recalculating the environment variables inside chef is a good idea. 1) We would have to do more than just copy the value of `toolchain.channel` and 2) if the api for *rust-toolchain.toml* changes at all, we would have to update chef.

If you can think of a better solution that doesn't change the chef's api, please let me know.

Going forward: I'm going to try to implement this in my fork, and once I'm done testing it I'll submit a PR.

**Comment by jsimonrichard** [comment] 2022-05-25 01:58
One other solution (although it's kind of a hack) is just to add `rustup default nightly` to the Dockerfile before `cargo chef cook` runs.

If you just want to go with this, we wouldn't be supporting `rust-toolchain.toml`, but it is an easy workaround.

**Comment by LukeMathWalker** [comment] 2022-07-04 15:47
The latest release of `cargo-chef` moves away from invoking `cargo` with an hard-coded path and leverages the dynamic `CARGO` environment variable that is set by `rustup`, correctly resolving the various sources for toolchain infos (`rust-toolchain.toml` files, overrides, etc.).

As you noted @jsimonrichard, there is indeed an execution order issue.
My suggestion is to copy over the `rust-toolchain.toml` file before calling the `cook` command, thus making sure that `cargo chef` is invoked using the desired toolchain from the get go. I think this should enough to solve the issue here.

**Closed by LukeMathWalker** 2022-07-04 15:47 UTC
