### ISSUE TITLE
Panic while running `cargo chef prepare`

### ISSUE THREAD

**Issue by imp** [LukeMathWalker/cargo-chef#60] opened 2021-05-02 17:38 UTC
I am getting this error while running `cargo chef prepare` (v0.1.20)

```
cargo chef prepare
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.20/src/skeleton.rs:65:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Same with `RUST_TRACEBACK=full` in case it might be useful

```
❯ RUST_BACKTRACE=full cargo chef prepare
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.20/src/skeleton.rs:65:34
stack backtrace:
   0:     0x56110e922df0 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x56110e922df0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56110e922df0 - std::sys_common::backtrace::_print_fmt::hfbda19e17f6db318
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56110e922df0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a8751bf59281272
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56110e947b2f - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/fmt/mod.rs:1094:17
   5:     0x56110e9202b5 - std::io::Write::write_fmt::hd7dd3a1df9b6befb
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/io/mod.rs:1580:15
   6:     0x56110e9252eb - std::sys_common::backtrace::_print::h551e9ec8a9fa8106
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56110e9252eb - std::sys_common::backtrace::print::ha4b1c5e95fa040b3
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56110e9252eb - std::panicking::default_hook::{{closure}}::h0b34c9ab7fb9f857
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:208:50
   9:     0x56110e924dcd - std::panicking::default_hook::h3067e8318decd17a
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:225:9
  10:     0x56110e92589d - std::panicking::rust_panic_with_hook::h81b8facc50f34daa
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:591:17
  11:     0x56110e925467 - std::panicking::begin_panic_handler::{{closure}}::ha376ab85d95a000e
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:495:13
  12:     0x56110e9232ac - std::sys_common::backtrace::__rust_end_short_backtrace::h6795c8afdd1a77e6
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x56110e9253f9 - rust_begin_unwind
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
  14:     0x56110e71f3c1 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:92:14
  15:     0x56110e71f30d - core::panicking::panic::h3de4db67bd397eb3
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:50:5
  16:     0x56110e79b4e7 - alloc::slice::<impl [T]>::sort_by::{{closure}}::h1eaf62c53785bfe8
  17:     0x56110e79b043 - alloc::slice::merge_sort::h47bf0508bd034a31
  18:     0x56110e7940e9 - chef::skeleton::Skeleton::derive::h67669d6be7fd637a
  19:     0x56110e78db4a - chef::recipe::Recipe::prepare::h1adbe7b566307dcb
  20:     0x56110e72c199 - cargo_chef::_main::h37403fc3b1dda56b
  21:     0x56110e725f16 - std::sys_common::backtrace::__rust_begin_short_backtrace::haae999a68f470d69
  22:     0x56110e725f2d - std::rt::lang_start::{{closure}}::h874d072e7514dd96
  23:     0x56110e925c9a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b8c329143d7638a
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/ops/function.rs:259:13
  24:     0x56110e925c9a - std::panicking::try::do_call::h4b72c261b4eefc1b
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:379:40
  25:     0x56110e925c9a - std::panicking::try::h703d31b7896cbd49
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:343:19
  26:     0x56110e925c9a - std::panic::catch_unwind::h37cad9b35388a915
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panic.rs:431:14
  27:     0x56110e925c9a - std::rt::lang_start_internal::hab5a8a909af4f90e
                               at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/rt.rs:51:25
  28:     0x56110e72db05 - main
  29:     0x7f90de175840 - __libc_start_main
  30:     0x56110e71fb59 - _start
  31:                0x0 - <unknown>
```

**Comment by LukeMathWalker** [comment] 2021-05-02 18:49
Hey!
To debug the issue I'll need access to the repository where you are experiencing the panic (or an equivalent minimal reproducible example).

**Comment by LukeMathWalker** [comment] 2021-05-09 14:55
Closing - I cannot reproduce without additional information.

**Closed by LukeMathWalker** 2021-05-09 14:55 UTC
