### ISSUE TITLE
Prepare stage ignores Cargo config

### ISSUE THREAD

**Issue by simon-bourne** [LukeMathWalker/cargo-chef#26] opened 2020-12-01 18:52 UTC
Hi, in my project I have `.cargo/config.toml`:

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=haswell"]
```

I currently have to copy my cargo config into my Docker `cacher` stage, so I'm caching and building with the same flags. Otherwise I get no caching, and no indication as to why.

It would be great if `cargo chef prepare` could emulate how cargo [finds and merges config files](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure), and include a merged `.cargo/confg.toml` in `recipe.json`.

Thanks,

Simon

**Comment by LukeMathWalker** [comment] 2020-12-04 07:55
Looking and adding to the recipe all the config files within the project tree is definitely something in scope - I wouldn't go all the way looking for stuff in $CARGO_HOME though.

**Comment by pythoneer** [comment] 2020-12-10 14:46
does that mean i can't use cargo-chef if i have multiple projects in my workspace that needs different targets to compile? I have a server that needs `x86_64-unknown-linux-gnu` and a client/website with `wasm32-unknown-unknown`. I am using `cargo-make` with `wasm-pack` to actually build my project but i figured its generally no problem for `cargo-make` if it is just using `cargo build commands`. I thought that i could have a `.cargo/config.toml` with
```toml
[build]
target = "wasm32-unknown-unknown"
``` 
to build the wasm dependencies. But it looks like the `cacher` stage is just caching x86 libs for my wasm project and builds them all again for wasm in the build stage (have not confirmed that but i was wondering why it is compiled twice in each stage and did not really cache it, unlike the server components)

**Comment by LukeMathWalker** [comment] 2021-02-27 14:32
#48 has just been merged into master - can you check if that solves your issue @simon-bourne?

**Closed** 2021-03-20 14:26 UTC
Labels: bug, good first issue
