### ISSUE TITLE
Support workspace inherited properties

### ISSUE THREAD

**Issue by Razican** [LukeMathWalker/cargo-chef#162] opened 2022-10-20 15:07 UTC
In Cargo 1.64, a new feature, workspace inheritance [was introduced](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds).

Cargo-chef doesn't yet enable this, and you get this error:

```
$cargo chef prepare --recipe-path recipe.json
Error: Failed to compute recipe
Caused by:
    0: invalid type: map, expected a string for key `package.repository` at line 8 column 24
    1: invalid type: map, expected a string for key `package.repository` at line 8 column 24
```

It would be nice to get this working. If I get some pointers on where can I find the code that is responsible for this, I can try to implement it myself :)

**Comment by LukeMathWalker** [comment] 2022-10-20 16:44
It should be easy enough, all the required infra is in place!
You need to change https://github.com/LukeMathWalker/cargo-manifest/blob/612ca32349d532672234d6023735ea0513e58775/src/lib.rs#L652 to use `MaybeInherited` like other fields in the same struct 😁

**Comment by dessalines** [comment] 2022-12-02 15:51
Also getting this issue.

**Comment by LukeMathWalker** [comment] 2022-12-07 08:45
The fix by @dessalines has been merged and released as part of 0.1.48.

**Comment by dessalines** [comment] 2022-12-09 16:12
This should maybe be reopened, as now I'm getting this issue on `0.1.48`

`error inheriting repository from workspace root manifest's workspace.package.repository `

So it really didn't fix anything.

**Comment by LukeMathWalker** [comment] 2022-12-09 16:30
Can you share more context around that error? Where is it coming from?

**Comment by dessalines** [comment] 2022-12-09 16:33
Step 15/24 : RUN cargo chef cook --recipe-path recipe.json --target ${CARGO_BUILD_TARGET}                                 ---> Running in 8222d78720f6                                                                                            error: failed to parse manifest at `/app/Cargo.toml`                                                                                                                                                                                              Caused by:                                                                                                                 error inheriting `repository` from workspace root manifest's `workspace.package.repository`                                                                                                                                                     Caused by:                                                                                                                 `workspace.package.repository` was not defined                                                                         thread 'main' panicked at 'Exited with status code: 101', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.48/src/recipe.rs:176:27

**Comment by dessalines** [comment] 2022-12-09 17:06
https://github.com/LemmyNet/lemmy/blob/main/Cargo.toml

**Comment by LukeMathWalker** [comment] 2022-12-09 17:22
The issue is that https://docs.rs/cargo-manifest/0.5.0/cargo_manifest/struct.WorkspacePackage.html doesn't have a `repository` field. 
I can patch it up tomorrow.

**Comment by LukeMathWalker** [comment] 2022-12-10 12:36
Done and released as `0.49.0`. Can you verify it succeeds @dessalines?

**Comment by dessalines** [comment] 2022-12-11 15:31
@LukeMathWalker thanks, it works! I'm guessing that version bump wasn't intentional, it used to be `0.1.48`.

**Comment by LukeMathWalker** [comment] 2022-12-11 19:47
You're right indeed - yanked and release `0.1.49` 😅

**Closed by LukeMathWalker** 2022-12-11 19:47 UTC
